# Generated by Django 3.1.3 on 2020-11-22 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='end_date_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='record',
            name='start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
