# Generated by Django 3.1.3 on 2020-11-24 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20201123_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='completed',
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='log.category'),
        ),
        migrations.AlterField(
            model_name='record',
            name='service_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='log.service'),
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='log.status'),
        ),
    ]
