# Generated by Django 3.1.3 on 2020-11-24 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20201124_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='log.category'),
        ),
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='log.service'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='log.status'),
        ),
    ]
