# Generated by Django 3.1.3 on 2020-11-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20201124_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='total_hours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
