# Generated by Django 3.1.3 on 2020-12-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20201127_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
