# Generated by Django 3.1.3 on 2020-12-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20201226_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='total_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
