# Generated by Django 3.1.3 on 2020-12-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20201226_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='end_date_time',
            field=models.DateTimeField(default=None),
        ),
    ]
